name: Quality

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality
    uses: Elavora/.github/.github/workflows/quality.yml@53066f062df3573aa619a86edfb119cdc43fe386
    with:
      extensions: json
      coverage_min: 80
